language: node_js

node_js:
    - "node"
    - "lts/*"
    - "11"
    - "10"

sudo: required

git:
    submodules: false

dist: xenial

addons:
  chrome: stable

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm install

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/

script:
    - npm test
