language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

addons:
    chrome: stable

services:
    - xvfb

git:
    submodules: false

before_script:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install

script:
    - npm test
