language: node_js

node_js:
    - "node"
    - "lts/*"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

dist: xenial

addons:
  chrome: stable

before_install:
  - wget http://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip
  - mkdir /chromedriver
  - unzip chromedriver_linux64.zip -d /chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm install

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - npm test
