language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

addons:
    chrome: stable

services:
    - xvfb

git:
    submodules: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - npm install

script:
    - npm test
